### PR TITLE
Added instances to preserve data between 1994 and 2000

### PR DESCRIPTION
**Pull request by RosaWagner**
I tried something on my side :) It does the interpolation thing, but doesn't preserve the "1992" data in the source.

### CODE REVIEW

**Comment by dancoull** [comment]
Thanks for trying Rosa :) So adding the extra masters didn't help to keep the retrograde part. Is there a way to view the file without merging into the main?

**Comment by dancoull** [comment]
Maybe it's still better to go with the original solution of an "average" instance?

**Comment by RosaWagner** [comment]
yes, you can download my branch https://github.com/RosaWagner/ClimateCrisis/tree/add-instances

**Comment by dancoull** [comment]
Hey Rosa, finally checked out the file :) When you said it didn't preserve the "1992" data, is it because it's now preserved in the master "2000" if I understand correctly?

**Comment by RosaWagner** [comment]
Euh… yes? I don't know anymore haha 
I think I meant, the date "1992" doesn't appear in the axis mapping anymore — which isn't a particular bad thing imo

**Comment by dancoull** [comment]
Haha :) don't worry it confuses me too. I agree tho, that mapping doesn't matter much as long as it represents what the users are supposed to see. I'll merge it now. Thanks for helping out and being patient :)

**Comment by dancoull** [comment]
Also meant to ask if you had an estimate on how long it will take to go live, are we still waiting for the custom axis registration?

**Comment by RosaWagner** [comment]
Ah yeah, Dave told me the axis registration is planned on 2022 1st quarter. So not before few month unfortunately.

**Comment by dancoull** [comment]
Cool, thanks! It's more the design agency we worked with keeps asking when it will be live :) Did we miss it for this year or does it just take long?

**Pull request merged**
